---
title: "Course Schedule"
output: 
  html_document:
    theme: cosmo
---

Each module starts at 6:00 pm on the date shown in the schedule. All the evaluations (exercise, homework, exam) must be submitted by 5:59 pm on their due dates before the next week module starts. The schedule is subject to change, and when it does, you will be notified through the Canvas course page. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(fontawesome)
library(kableExtra)
```

```{css, echo=FALSE}
p {
 font-size: 18px;
}
```

```{r dates, echo=FALSE}
start <- as.Date("2020-09-02")

week_after <- function(adv){
  wdate <- start + 7*(adv-1)
  wdate <- format(wdate, format="%m/%d")
  zadv <- sprintf("%02d", adv)
  wstr <- paste0("Week ",zadv,sep='',' (', wdate, ')')
  wstr
}

due_in <- function(week, due){
  tmp2 <- start + 7*(week-1+due)
  tmp2 <- format(tmp2, format="%m/%d")
  tmp2
}
```

```{r schedule, echo=FALSE}
n = 1:16
date = week_after(n)
topic = c(
  'Intro to data mining and toolkit',
  'R basics',
  'Workflow: R markdown and Git/Github',
  'Data visualization 1 (ggplot2)',
  'Exploratory data analysis (dplyr)',
  'Data transformation (dplyr)',
  'Data visualization 2 (ggplot2)',
  'Data import and export',
  'Tidy data (tidyr)',
  'Joining data (dplyr)',
  'Regression 1 (Univariate)',
  'Regression 2 (Multivariate, model selection)',
  'Decision tree',
  'Clustering',
  'Tidytext and sentiment analysis',
  'Intro to machine (and deep) learning'
)

# URL must include https or http
slide_links <- c(
  "https://www.google.com",
  "www.google.com",
  "www.google.com",
  "www.google.com",
  "www.google.com",
  NA,
  "www.google.com",
  "www.google.com",
  "www.google.com",
  "www.google.com",
  NA,
  "www.google.com",
  "www.google.com",
  "www.google.com",
  "www.google.com",
  "www.google.com"
)

dc_links <- c(
  "dc1.html",
  "lab1.html",
  "www.google.com",
  "www.google.com",
  "www.google.com",
  NA,
  "www.google.com",
  "www.google.com",
  "www.google.com",
  "www.google.com",
  NA,
  "www.google.com",
  "www.google.com",
  "www.google.com",
  "www.google.com",
  "www.google.com"
)

hw_links <- c(
  "hw1.html",
  "www.google.com",
  "www.google.com",
  "www.google.com",
  "www.google.com",
  NA,
  "www.google.com",
  "www.google.com",
  "www.google.com",
  "www.google.com",
  NA,
  "www.google.com",
  "www.google.com",
  "www.google.com",
  "www.google.com",
  "www.google.com"
)

exam_links <- c(
  NA,
  NA,
  NA,
  NA,
  NA,
  NA,
  NA,
  NA,
  NA,
  "midterm_instruction.html",
  NA,
  NA,
  NA,
  NA,
  NA,
  "final_instruction.html"
)

addLink <- function(link, img, color) {
  paste0("<a href=\"", link, "\">", as.character(fa(name = img, fill = color)), "</a>")
}
noLink <- function(img, color) {
  fa(name = img, fill = color)
}

addicon <- function(i, img){
  if (is.na(i)==FALSE) {
    addLink(i, img, 'steelblue')
  }
  else {
    noLink(img, 'lightblue')
  }
}

slide <- sapply(slide_links, addicon, img='folder')
dc <- sapply(dc_links, addicon, img='flask')
hw <- sapply(hw_links, addicon, img='code')
exam <- sapply(exam_links, addicon, img='edit')

df <- tibble(
  Date=date,
  Topic=topic,
  Slide=slide,
  Lab=dc,
  HW=hw,
  Exam=exam
)
# knitr::kable(df) 
knitr::kable(df, escape = F) %>%
  kable_styling(bootstrap_options = "striped", font_size = 18)
```
