---
title: "Homework 1 - Data wrangling and visualization"
output: 
  html_document: 
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Release: 10/07/2020**  
**Due: 10/21/2020**

In this homework, you will write R codes to answer the below questions regarding the flights that departed New York City in 2013. Each question involves some form of data wrangling and data visualization, which we've covered until this week. Before you start, please read the below instructions carefully as failure to follow the instructions may result in deductions in your score.

# Before you start ...
## Instructions

- Download the source Rmd file from the `Code` tab at the upper-right corner of this document.
- In the YAML header, change `author` to your name.
- For each question, write your R code inside the R chunk, starting below the line `# write your code below this comment line`
  - one answer for each question
- You must write your code **inside** the R chunks. Do not change anything else (e.g., chunk options, order of question)
- Do not add additional R chunks

## Submission

- Save your R markdown document as "lastname_firstname_WSUID.Rmd" (e.g., lee_kyunghee_gl3566.Rmd)
- Submit your `Rmd` file on **Canvas**
  - You only need to submit the `Rmd` file, not the output `html` document which is generated from the `Rmd` file. 

## Grading

- 15 questions in total, each accounts for 1 point
- **To get the full score for each question, your code must be executable without generating any errors**
- If your code doesn't run, partial credits will be given.
